### ISSUE TITLE
无法上传配置到云

### ISSUE THREAD

**Issue by ChaosTong** [easychen/checkchan-dist#1]
docker 当前version 2 版本部署， mac端Microsoft Edge版本 83.0.478.37
点击 通过云服务器检测 报错，尝试给插件加 <all_urls> 权限，依旧无效
![截屏2022-05-23 00 01 45](https://user-images.githubusercontent.com/3345527/169704650-da0e7108-788b-41fe-ad1b-bf336102d504.png)

尝试手动将导出的json文件传到 /data 路径中，缺少cookies字段报错， 手动加入 cookies字段后，在列表页点`监测`正常使用， 但是在编辑页面尝试测试，弹检测失败提示Tip

**Comment by easychen** [comment]
edge版本有点低，升级到最新版试试。

**Comment by ChaosTong** [comment]
上传配置的问题 升级就好了
在列表页点监测正常使用， 但是在编辑页面尝试测试，弹检测失败提示Tip 还是存在
列表里单独点监测，本地提示`检测内容为空`，切成云端显示dom对应内容

**Comment by ChaosTong** [comment]
更新了插件, edge没试, chrome正常了
