### ISSUE TITLE
docker在VNC OFF条件下，本地checks/upload 不返回结果。

### ISSUE THREAD

**Issue by chaoticjoy** [easychen/checkchan-dist#16]
打开VNC后，连接第一次显示有个unlock，点击后checks/upload才可以用

**Comment by easychen** [comment]
> 打开VNC后，连接第一次显示有个unlock，点击后checks/upload才可以用

感谢反馈，我查了下，不是因为unlock问题，而是因为DEV标志位判断有误导致未打开VNC时，启用了开发用server。这个问题已经在最新的镜像（ [2022.06.14.22.27](https://hub.docker.com/layers/234148943/easychen/checkchan/2022.06.14.22.27/images/sha256-ab4f7aa8842bc790b6fdf42f5bd46af11ce858d7f2317fcf5ee91cce3b305f5e?context=repo) ）中修复了，可以 pull 更新下。
