### ISSUE TITLE
关于发送消息

### ISSUE THREAD

**Issue by ixinshang** [easychen/checkchan-dist#17]
请问一下，check酱的消息推送渠道是否是全部通过server酱，然后转发绑定的微信应用、机器人以及 WebHook 等通道？ 是否每发送一次，增加一次“每天最多发送条数”？
 WebHook  是否受每天最多发送条数的数量影响！

谢谢

**Comment by easychen** [comment]
除了server酱，还有浏览器通知和mqtt两个其他的消息通道。所有走server酱的推送都会受配额限制，包括webhook。
