### ISSUE TITLE
无法选到内容

### ISSUE THREAD

**Issue by abxm2** [easychen/checkchan-dist#2]
https://tronscan.org/#/contract/TEkxiTehnzSmSe2XqrBj4w32RUN966rdz8/transfers
在这个网页下的记录，下面Transfer默认是【trx transfer】， 如何选到【trc20】下的记录？
目前选择器选择，因为这两个transfer记录的选择器是一样的，只能选到默认的【trx transfer】下的记录，比如 amount
![image](https://user-images.githubusercontent.com/47627026/171093771-cb1c578a-c4ff-43c7-8bf8-1781d2ed5ef7.png)

**Comment by easychen** [comment]
https://www.bilibili.com/video/BV1K94y1m7tt?t=2153.1
