### ISSUE TITLE
经常收到关于来自云端@172.17.0.9的错误信息

### ISSUE THREAD

**Issue by itgoyo** [easychen/checkchan-dist#26]
![image](https://user-images.githubusercontent.com/23348551/181499505-23e115be-452e-4d89-9fc4-14e7605c4323.png)

大大，从一开始用到现在最新版本，我这边的novnc跑的方式，总是会收到这种类似的通知，相当于我挂了几个任务，它经常一下子就发几条类似的这种错误消息过来。

出现这种情况最高的频率是我关电脑后一会，或者个吧小时，但是电脑开着的时候就好像很少出现这种连续发错误的提醒，但是还是会偶尔有，不知道有没有别的小伙伴出现过类似的情况没有。

我这边都是浏览器弄好，然后导出json文件，然后novnc远程的check酱上面再手动导入json数据的，每次我在浏览器上面点击同步，它都会提示已同步，但是novnc上面的版本就是不会出现任务，都是需要手动上传才出现任务。配置的云端地址还有API KEY都校验过，重点是显示log的视图里是可以看到后台运行的情况的，但就是在任务栏上面不会出现。

新版本的docker默认不改分辨率的话，在新的模块发现里面是看不到左下角蓝色的『监测更新』，需要修改手机的分辨率才能显示出来，就如果没看视频的话，估计是不知道这里还有这个按钮，所以可不可以下次把按钮放高一点呀。

**Comment by easychen** [comment]
首先，浏览器插件上的同步按钮是同步到云端，不会同步到远程桌面（VNC）。云端和远程桌面是两个东西，远程桌面只是装到服务器上的又一个浏览器而已。

报错很可能是因为关机以后cookie不再同步了。

按钮用的是相对位置，看不到很可能是NO VNC的窗口不合适，可以通过 docker-compose 中的环境变量调整。

**Comment by itgoyo** [comment]
好的，明白了，感谢大大的回复
