### ISSUE TITLE
浏览器插件版经常第二天开机起来就发现插件错误了

### ISSUE THREAD

**Issue by itgoyo** [easychen/checkchan-dist#27]
<img width="693" alt="image" src="https://user-images.githubusercontent.com/23348551/181664998-d6bbbdfb-c158-457c-90bc-f963d5c3f6a0.png">

昨天早上也有一次早上开机找不到浏览器图标，然后发现插件错误了之后自动停用了，大概是一个weibo相关字眼的错误，当时没太在意

然后今天早上开机，发现插件图标又不见了，又到插件管理中心重新启用，这次截了一张图，应该不是偶发。

**Comment by itgoyo** [comment]
补充，插件是前三天的时候弄的，现在看到有个7.28的版本，我再试试这个版本看看效果

**Comment by easychen** [comment]
这个bug修复了，可以下载今天的版本。
