### ISSUE TITLE
7.28更新的docker版本docker pull重开新docker，出现Failed to load extension from:/checkchan/extension/的错误 

### ISSUE THREAD

**Issue by itgoyo** [easychen/checkchan-dist#28]
<img width="532" alt="image" src="https://user-images.githubusercontent.com/23348551/181667523-f2562b93-2ab0-404e-a0eb-8a2c25360137.png">
<img width="528" alt="image" src="https://user-images.githubusercontent.com/23348551/181667538-76e791f9-e570-41a5-8bc8-0f3a5e65f9e3.png">

**Comment by easychen** [comment]
最新版的chromium 有bug，重新打包了一个版本  https://hub.docker.com/layers/262547623/easychen/checkchan/2022.07.29.13.10/images/sha256-6c51a82c123af21378d2a6b614574ab61bf6a1e8fb848bf99e6ae61ceb254e46?context=repo
