### ISSUE TITLE
[功能请求] 把教程做成gitbook wiki形式

### ISSUE THREAD

**Issue by zzz6839** [easychen/checkchan-dist#29]
目前的文字教程（readme）没有侧边折叠目录，检索起来不方便。

**Comment by easychen** [comment]
这里有 
![image](https://user-images.githubusercontent.com/1294760/181770310-1ccc2bf1-33a8-402d-95bd-b777bb7ab412.png)

**Comment by easychen** [comment]
那你可以去 gitee 看  https://gitee.com/easychen/checkchan-dist 
![image](https://user-images.githubusercontent.com/1294760/181772678-631575fd-f636-45c1-8c29-c044061f250f.png)
