### ISSUE TITLE
b站视频标题会只出现NEW的变化

### ISSUE THREAD

**Issue by zhangsheng377** [easychen/checkchan-dist#30]
比如：
02:17:57 《古墓丽影 : 崛起》电影版 【4K | 21:9宽银幕】中英文双语字幕←02:17:57 NEW 《古墓丽影 : 崛起》电影版 【4K | 21:9宽银幕】中英文双语字幕

这种其实不该二次提醒，请问有什么办法吗？

**Comment by easychen** [comment]
可以用最新版本里边的 忽略文本选择器把  NEW 选中，这样最终结果就没有它了  

类似这样 
![image](https://user-images.githubusercontent.com/1294760/182025391-1983425d-6b0f-40da-aa34-4d871baed8a0.png)

**Comment by zhangsheng377** [comment]
> 

但是这样的话，原先忽略的meta，就会出现了。。。
div#submit-video-list > ul:nth-of-type(2) > li:nth-of-type(1) .meta

**Comment by easychen** [comment]
> > 
> 
> 但是这样的话，原先忽略的meta，就会出现了。。。 div#submit-video-list > ul:nth-of-type(2) > li:nth-of-type(1) .meta

多个selector之间可以用逗号隔开的。

**Comment by zhangsheng377** [comment]
> > > 
> > 
> > 
> > 但是这样的话，原先忽略的meta，就会出现了。。。 div#submit-video-list > ul:nth-of-type(2) > li:nth-of-type(1) .meta
> 
> 多个selector之间可以用逗号隔开的。

ok啦~~这样填就行啦~~
div#submit-video-list > ul:nth-of-type(2) > li:nth-of-type(1) .meta, .be-tags-container
谢谢~~
