### ISSUE TITLE
2022.8.1 docker拉取最新版本运行之后8088一直错误

### ISSUE THREAD

**Issue by itgoyo** [easychen/checkchan-dist#32]
```
sudo docker run -d -p 8088:80 -p 4080:8080 -p 5900:5900 -v ${PWD}/data:/checkchan/data -e API_KEY=guaijiu12345 -e VDEBUG=OFF -e WIN_WIDTH=414 -e WIN_HEIGHT=896 -e XVFB_WHD=500x896x16 -e VNC=ON -e SNAP_URL_BASE=http://42.193.xxx.xxx:8088 -e CKC_PASSWD=guaijiu12345 -e TZ=Asia/Chongqing easychen/checkchan:latest
```
`http://42.193.xxx.xxx:8088`这个写的是真实的服务器ip，确保无误，而且之前都是这样子运行的

<img width="328" alt="image" src="https://user-images.githubusercontent.com/23348551/182077987-8b014fe3-ab43-4e20-b43e-830b93084476.png">

容器的日志：
<img width="1119" alt="image" src="https://user-images.githubusercontent.com/23348551/182078041-813f4d0a-6ede-45ba-927c-523b49b21839.png">

<img width="1366" alt="image" src="https://user-images.githubusercontent.com/23348551/182078242-66d6714e-c46b-4b95-9da6-8493f1e9372e.png">

**Comment by easychen** [comment]
这是个bug，等我重新打包一下。

**Comment by easychen** [comment]
你试试  2022.08.01.14.10 版本
