### ISSUE TITLE
云端运行任务满足条件不发送通知

### ISSUE THREAD

**Issue by Xm798** [easychen/checkchan-dist#35]
使用云端运行任务，检测到值为“闲置”，设置触发条件为“!=运行中”，但并未正常触发通知。

手动点击监测，正常。

<img width="677" alt="image" src="https://user-images.githubusercontent.com/48074861/182552679-409197cd-f497-4669-b06b-0957442035e1.png">

任务日志如下：

```log
[2022-08-03 15:43:01]开始载入任务
[2022-08-03 15:43:01]Alas...条件检查 true
[2022-08-03 15:43:01]checking...Alas
[2022-08-03 15:43:04]{"status":true,"value":"闲置","type":"dom","link":""}
[2022-08-03 15:43:04]条件比较模式

[2022-08-03 15:44:01]开始载入任务
[2022-08-03 15:44:01]Alas...条件检查 false
[2022-08-03 15:44:01]全部任务处理完成

[2022-08-03 15:45:01]开始载入任务
[2022-08-03 15:45:01]Alas...条件检查 true
[2022-08-03 15:45:01]checking...Alas
[2022-08-03 15:45:03]{"status":true,"value":"闲置","type":"dom","link":""}
[2022-08-03 15:45:03]条件比较模式
```

任务配置如下：
```json
{
    "checks": [
        {
            "id": "xxx",
            "title": "Alas",
            "enabled": 1,
            "is_cloud_task": 1,
            "url": "xxx",
            "icon": "xxx",
            "page": "",
            "path": "div#pywebio-scope-header_status > div > p",
            "ignore_path": "",
            "click_path": "",
            "scroll_down": "0",
            "type": "dom",
            "code": "200",
            "json_query": "",
            "json_header": "",
            "json_data": "",
            "json_data_format": "form",
            "rss_field": "title",
            "star": 0,
            "ua": "",
            "puppeteer_code": "search_btn = await page.$('#pywebio-scope-aside > div:nth-child(2) > div:nth-child(2) > button');\nawait search_btn.click();",
            "browser_code": "",
            "shell_type": "javascript",
            "shell_cookie_name": "COOKIE",
            "shell_code": "",
            "replace_from_regex": "",
            "replace_to_regex": "",
            "interval": "1",
            "delay": "0",
            "retry": 10,
            "cron": "* * * * *",
            "sendkey": "xxx",
            "send_channel": "18",
            "regex": "",
            "when": "every",
            "compare_type": "op",
            "compare_op": "ne",
            "compare_value": "运行中",
            "retry_times": 0,
            "last_content": "闲置",
            "last_time": 1659512464012
        }
    ],
    "cookies": {
        "xxx": []
    }
}

```

**Comment by Xm798** [comment]
更新：尝试使用正则`^((?!运行中).)*$`，可以正常发送通知。

**Comment by easychen** [comment]
> 使用云端运行任务，检测到值为“闲置”，设置触发条件为“!=运行中”，但并未正常触发通知。
> 
> 手动点击监测，正常。
> 
> <img alt="image" width="677" src="https://user-images.githubusercontent.com/48074861/182552679-409197cd-f497-4669-b06b-0957442035e1.png">
> 
> 任务日志如下：
> 
> ```
> [2022-08-03 15:43:01]开始载入任务
> [2022-08-03 15:43:01]Alas...条件检查 true
> [2022-08-03 15:43:01]checking...Alas
> [2022-08-03 15:43:04]{"status":true,"value":"闲置","type":"dom","link":""}
> [2022-08-03 15:43:04]条件比较模式
> 
> [2022-08-03 15:44:01]开始载入任务
> [2022-08-03 15:44:01]Alas...条件检查 false
> [2022-08-03 15:44:01]全部任务处理完成
> 
> [2022-08-03 15:45:01]开始载入任务
> [2022-08-03 15:45:01]Alas...条件检查 true
> [2022-08-03 15:45:01]checking...Alas
> [2022-08-03 15:45:03]{"status":true,"value":"闲置","type":"dom","link":""}
> [2022-08-03 15:45:03]条件比较模式
> ```
> 
> 任务配置如下：
> 
> ```json
> {
>     "checks": [
>         {
>             "id": "xxx",
>             "title": "Alas",
>             "enabled": 1,
>             "is_cloud_task": 1,
>             "url": "xxx",
>             "icon": "xxx",
>             "page": "",
>             "path": "div#pywebio-scope-header_status > div > p",
>             "ignore_path": "",
>             "click_path": "",
>             "scroll_down": "0",
>             "type": "dom",
>             "code": "200",
>             "json_query": "",
>             "json_header": "",
>             "json_data": "",
>             "json_data_format": "form",
>             "rss_field": "title",
>             "star": 0,
>             "ua": "",
>             "puppeteer_code": "search_btn = await page.$('#pywebio-scope-aside > div:nth-child(2) > div:nth-child(2) > button');\nawait search_btn.click();",
>             "browser_code": "",
>             "shell_type": "javascript",
>             "shell_cookie_name": "COOKIE",
>             "shell_code": "",
>             "replace_from_regex": "",
>             "replace_to_regex": "",
>             "interval": "1",
>             "delay": "0",
>             "retry": 10,
>             "cron": "* * * * *",
>             "sendkey": "xxx",
>             "send_channel": "18",
>             "regex": "",
>             "when": "every",
>             "compare_type": "op",
>             "compare_op": "ne",
>             "compare_value": "运行中",
>             "retry_times": 0,
>             "last_content": "闲置",
>             "last_time": 1659512464012
>         }
>     ],
>     "cookies": {
>         "xxx": []
>     }
> }
> ```

这里只能填数值

**Comment by Xm798** [comment]
> > 使用云端运行任务，检测到值为“闲置”，设置触发条件为“!=运行中”，但并未正常触发通知。
> > 手动点击监测，正常。
> > <img alt="image" width="677" src="https://user-images.githubusercontent.com/48074861/182552679-409197cd-f497-4669-b06b-0957442035e1.png">
> > 任务日志如下：
> > ```
> > [2022-08-03 15:43:01]开始载入任务
> > [2022-08-03 15:43:01]Alas...条件检查 true
> > [2022-08-03 15:43:01]checking...Alas
> > [2022-08-03 15:43:04]{"status":true,"value":"闲置","type":"dom","link":""}
> > [2022-08-03 15:43:04]条件比较模式
> > 
> > [2022-08-03 15:44:01]开始载入任务
> > [2022-08-03 15:44:01]Alas...条件检查 false
> > [2022-08-03 15:44:01]全部任务处理完成
> > 
> > [2022-08-03 15:45:01]开始载入任务
> > [2022-08-03 15:45:01]Alas...条件检查 true
> > [2022-08-03 15:45:01]checking...Alas
> > [2022-08-03 15:45:03]{"status":true,"value":"闲置","type":"dom","link":""}
> > [2022-08-03 15:45:03]条件比较模式
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 任务配置如下：
> > ```json
> > {
> >     "checks": [
> >         {
> >             "id": "xxx",
> >             "title": "Alas",
> >             "enabled": 1,
> >             "is_cloud_task": 1,
> >             "url": "xxx",
> >             "icon": "xxx",
> >             "page": "",
> >             "path": "div#pywebio-scope-header_status > div > p",
> >             "ignore_path": "",
> >             "click_path": "",
> >             "scroll_down": "0",
> >             "type": "dom",
> >             "code": "200",
> >             "json_query": "",
> >             "json_header": "",
> >             "json_data": "",
> >             "json_data_format": "form",
> >             "rss_field": "title",
> >             "star": 0,
> >             "ua": "",
> >             "puppeteer_code": "search_btn = await page.$('#pywebio-scope-aside > div:nth-child(2) > div:nth-child(2) > button');\nawait search_btn.click();",
> >             "browser_code": "",
> >             "shell_type": "javascript",
> >             "shell_cookie_name": "COOKIE",
> >             "shell_code": "",
> >             "replace_from_regex": "",
> >             "replace_to_regex": "",
> >             "interval": "1",
> >             "delay": "0",
> >             "retry": 10,
> >             "cron": "* * * * *",
> >             "sendkey": "xxx",
> >             "send_channel": "18",
> >             "regex": "",
> >             "when": "every",
> >             "compare_type": "op",
> >             "compare_op": "ne",
> >             "compare_value": "运行中",
> >             "retry_times": 0,
> >             "last_content": "闲置",
> >             "last_time": 1659512464012
> >         }
> >     ],
> >     "cookies": {
> >         "xxx": []
> >     }
> > }
> > ```
> 
> 这里只能填数值

但是本地运行正常，手动测试也正常。

**Comment by easychen** [comment]
<img width="1461" alt="image" src="https://user-images.githubusercontent.com/1294760/182877309-a0e5e5e8-10a9-4ed0-bfd2-0d5d0bc70ea7.png">

手动测试（即使是云端项目）是走的本地比较和通知系统。查了下云端和插件的比较代码是一样的，等有时间我再看看。
