### ISSUE TITLE
插件版和docker版关于最后的刷新时间不对的问题

### ISSUE THREAD

**Issue by itgoyo** [easychen/checkchan-dist#36]
所有任务我这边基本都是设置的10min检测一次,但是每次看到面板的最后刷新时间经常都是没变化的，但是小说的更新推送是可以收到的，就是面板的读取到的更新内容展示不对，和最后的刷新时间不对

最后的刷新时间都是几天之前，之前以为我是同步到云端运行的原因，后面我用远程nvc版本挂电脑图标【也就是云端本地运行】也会出现最后时间不对的问题，都会大于我设定的10min检测一次

<img width="826" alt="image" src="https://user-images.githubusercontent.com/23348551/182767804-e3ee64ad-262c-421c-967d-666697489bdd.png">
<img width="1252" alt="image" src="https://user-images.githubusercontent.com/23348551/182767956-15a18fd8-74c6-4982-8e0d-ad5050e45435.png">

![image](https://user-images.githubusercontent.com/23348551/182768276-44417d23-19d6-46c0-8cba-b8b4bb04f557.png)

<img width="1135" alt="image" src="https://user-images.githubusercontent.com/23348551/182770692-8c95197e-bf86-4f28-b172-94157b9a59fd.png">

**Comment by easychen** [comment]
那个不是最近任务执行时间，是最近返回结果有变动的时间…

**Comment by easychen** [comment]
云端任务的执行时间不会自动同步到浏览器插件里边，需要手工点同步。

至于VNC里边的浏览器时间不正常，我暂时猜不出来什么原因（因为它完全就是用插件的代码），或许和服务器时区有关。
