### ISSUE TITLE
云端返回值处理时检测参数重复

### ISSUE THREAD

**Issue by JokerQyou** [easychen/checkchan-dist#37]
无意间看到的，具体代码是这里：

https://github.com/easychen/checkchan-dist/blob/bc6cf4fb97daa7f7addbbd1a45254843303854ff/docker/api/cron.js#L68

应该是 `if( item.replace_from_regex && item.replace_to_regex )` 吧？

另外“返回值”处理这部分完全没有文档，教程视频里似乎也没有提到。在后续的收费教程中是否有这部分的内容呢？

**Comment by easychen** [comment]
嗯嗯，这个是笔误，最新版已经修复了
