### ISSUE TITLE
[Feature Request] Webhook 是否可以带上任务名称

### ISSUE THREAD

**Issue by JokerQyou** [easychen/checkchan-dist#38]
目前仅有 `id` 和 `url`，但是这两个值对于事件的接收方来说并没有太大意义，因为任务定义只在发送方有。建议增加一个参数 `name` 把任务名称一起发送出去。

**Comment by zhangsheng377** [comment]
咦，这个webhook你调用起来了吗？怎么配置的呀？

**Comment by JokerQyou** [comment]
> 咦，这个webhook你调用起来了吗？怎么配置的呀？

呃，插件设置页面不就能设置吗？容器的话通过环境变量设置，文档里已经写得很清楚了。

**Comment by zhangsheng377** [comment]
> 

额。。。我也是在这边填写的，我填的是钉钉的机器人地址，为啥就没反应呢？。。
#25

**Comment by JokerQyou** [comment]
钉钉机器人又不能直接解析Check酱发送的数据，你肯定要自己写程序处理然后转发到钉钉啊。

**Comment by hurae** [comment]
如果直接用来发送通知的话，我觉得只需要 name，value 和 link。html 字段甚至都足够用来自行编写奇奇怪怪的匹配逻辑了。

**Comment by onesecurity** [comment]
https://github.com/easychen/checkchan-dist/pull/52
我贡献到这里了，等 @easychen 审批确认是否合入。

**Comment by easychen** [comment]
> #52 我贡献到这里了，等 @easychen 审批确认是否合入。

webhook不提供name字段，请根据id自行补全。

**Comment by JokerQyou** [comment]
> webhook不提供name字段，请根据id自行补全。

可否展开说一下？作为 webhook 的接收方并不持有任务的定义，只有 Check酱 自身有这个信息，如何能够根据任务 id 补全呢？

**Comment by easychen** [comment]
> 

让任务创建人自己填id对应的name就行。提供name字段可能导致部分用户使用webhook绕开内置通知系统，而内置通知是Check酱作为免费软件提供的前提，因此我们会进行限制。
