### ISSUE TITLE
生成rss上传

### ISSUE THREAD

**Issue by zhangsheng377** [easychen/checkchan-dist#39]
仓库里的rss_upload文件，怎么用的呀？

**Comment by chinobing** [comment]
当正常的php网站部署， 然后填上对应的`rss_upload.php`地址
![image](https://user-images.githubusercontent.com/27722028/183260354-623d6109-49c1-4551-836d-f20088b7fd63.png)

然后->“动态”， 点击"RSS“上传
![image](https://user-images.githubusercontent.com/27722028/183260386-71177de9-3cb8-4721-82c7-7ee4149a7307.png)

最后打开`https://example.com/rss.php` 即可

**Comment by zhangsheng377** [comment]
> 当正常的php网站部署， 然后填上对应的`rss_upload.php`地址 ![image](https://user-images.githubusercontent.com/27722028/183260354-623d6109-49c1-4551-836d-f20088b7fd63.png)
> 
> 然后->“动态”， 点击"RSS“上传 ![image](https://user-images.githubusercontent.com/27722028/183260386-71177de9-3cb8-4721-82c7-7ee4149a7307.png)
> 
> 最后打开`https://example.com/rss.php` 即可 ![image](https://user-images.githubusercontent.com/27722028/183260465-98fe0cbe-4ee3-4fa1-ba76-a6d0f2e627ac.png)

赞~~已经弄起来啦~~~~但为什么动态只能显示本地任务的呢？。。。云端任务为啥没有动态呀？

**Comment by chinobing** [comment]
记得作者解释过，好像就是这样设计的。要么用VNC版本，云端上的check酱

**Comment by zhangsheng377** [comment]
> 记得作者解释过，好像就是这样设计的。要么用VNC版本，云端上的check酱

好吧。。。但这样有点麻烦啊。。。就算用vnc，rss的更新也不能及时。。。
