### ISSUE TITLE
DOM文本能添加XPath支持吗？目前只有CSS Selector

### ISSUE THREAD

**Issue by norlight** [easychen/checkchan-dist#41]

**Comment by easychen** [comment]
有什么特别的理由吗？

**Comment by norlight** [comment]
就目前试用的发现页的一些示例，三天两头失效，推送的都是重试失败，看了下DOM感觉用XPath的话会稳不少。
XPath更擅长定位标签本身，比如我可以以某标签内容文本作为条件进行其他定位。当然我之前是XPath用得比较多，可能CSS Selector也能做到，只是我没怎么用过没发现。这也是一个理由，用户熟悉哪个用哪个，减少学习成本。

**Comment by easychen** [comment]
看了一下文档，感觉以目前的实现支持起来比较麻烦，以后再说吧
