### ISSUE TITLE
Webhook 建议添加占位符支持

### ISSUE THREAD

**Issue by AemonCao** [easychen/checkchan-dist#42]
webhook 这里能否添加占位符，因为我使用的 bark 推送服务，又不想写接口转发，默认发送的 post 请求，bark 好像不太能解析。所以能不能添加一下占位符的支持。

然后默认发送的 post 请求中最好能够添加一下任务id所对应的任务名称字段，在通知显示这方面，比起任务的id，任务名称会更加易于识别。

**Comment by easychen** [comment]
如果你不想自己写接口，那么请使用内置的Server酱进行转发（支持bark）。webhook并不是为对接其他通知接口设计的。
