### ISSUE TITLE
去除 docker 镜像打包中的 .git 目录

### ISSUE THREAD

**Issue by hurae** [easychen/checkchan-dist#46]
在用于 production 的镜像中包含 .git 目录是没有必要的，而且还增加了存储大小，带来了轻微的风险，便于攻击者明确得知具体的小版本。建议打包 docker 镜像时去掉所有的 .git 目录。

具体包括：

- /checkchan/noVNC/.git
- /checkchan/noVNC/utils/websockify/.git

**Comment by easychen** [comment]
这个的确可以去掉，下一个版本更新时处理。
