### ISSUE TITLE
关于云端与与远程桌面合并后的提议

### ISSUE THREAD

**Issue by nekolr** [easychen/checkchan-dist#5]
首先感谢作者做出这个项目。然后能否保留之前的云端，在脚本里通过判断没有设置相关环境变量时不启动 vnc。

**Comment by Robotmaid** [comment]
同意，能不能提供回退的版本呀，我更新之后，服务器资源不够。

**Comment by easychen** [comment]
最新版镜像添加了VNC开关，不需要 VNC 的可以把 VNC=ON 改为 VNC=OFF
