### ISSUE TITLE
Docker配置问题

### ISSUE THREAD

**Issue by wpv-chan** [easychen/checkchan-dist#6]
开发者你好，我想问问这个云端的有架构限制什么的吗？
在arm设备上部署后启动时会有如下报错信息：
stderr: exec /checkchan/shell/docker-entrypoint.sh: exec format error

**Comment by easychen** [comment]
当前镜像是x86的，不支持 arm。arm可以自行从 dockerfile 构建。

**Comment by easychen** [comment]
我重新编译了一个 arm 版的，你再拉取试试

**Comment by wpv-chan** [comment]
可以了，感谢



---Original---
From: ***@***.***&gt;
Sent at: 2022年6月3日(Fri) Early Morning3:19
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [easychen/checkchan-dist] Docker配置问题 (Issue #6)




 
我重新编译了一个 arm 版的，你再拉取试试
