### ISSUE TITLE
超过最大重试次数后，检测任务始终跳过

### ISSUE THREAD

**Issue by Robotmaid** [easychen/checkchan-dist#7]
之前断了一段时间的网，后来发现检测任务很久不工作，按F12发现是“重试次数超过，跳过”。需要一个个手动点击检测，能不能加个提示该任务重试次数超过的标记，或者加个一键探测所有重试次数超过任务的按钮。

**Comment by Rainman1124** [comment]
碰到同样的问题。

**Comment by easychen** [comment]
再点一次「暂停/继续」或者「监测」按钮就重置了
