### ISSUE TITLE
docker版本疑似云同步有问题 我点击下载查看内容正常但是为啥我电脑提交的任务在云服务器那边不显示

### ISSUE THREAD

**Issue by lozn00** [easychen/checkchan-dist#70]
但是在云服务器那边点击下载查看内容是正常的啊，但是这看不到任务在执行

**Comment by easychen** [comment]
去看下发现页面的教程，我记得一个任务要么在云端要么在本地，任务状态是不同步的，任务同步只能同步任务本身，不附带额外信息。
