### ISSUE TITLE
关于监测间隔时间

### ISSUE THREAD

**Issue by StrollStars** [easychen/checkchan-dist#75]
发现这个值可以设置成0甚至是负值，请问这个时候实际执行是怎么样的？是不是按最低一分钟处理？

**Comment by easychen** [comment]
对。

**Comment by StrollStars** [comment]
@easychen 那可否像监测周期限制那样，支持日周月的设置？有些网页不需要那么频繁，虽然分钟也能实现，但是数值就变得很大了。
