### ISSUE TITLE
check能否不使用server酱，提供支持自定义webhook功能

### ISSUE THREAD

**Issue by wintsa123** [easychen/checkchan-dist#79]
server酱收费。。。不花钱的话只能一天推送5条，如果是这样的话，还不如由服务器直接推送到webhook上，毕竟checkchan是支持服务端部署的

**Comment by easychen** [comment]
① Check酱是支持webhook的，就在设置页面。 

![image](https://github.com/easychen/checkchan-dist/assets/1294760/3fb5d8e4-9982-46be-9f77-dd060b692d5e)

② Check酱是 Server酱赞助开发的，如果 Server酱一直挣不到钱，Check酱可能就没了。一个月就3块钱也不多吧

**Comment by wintsa123** [comment]
> ① Check酱是支持webhook的，就在设置页面。
> 
> ![image](https://private-user-images.githubusercontent.com/1294760/344532228-3fb5d8e4-9982-46be-9f77-dd060b692d5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MTM1NzgsIm5iZiI6MTcxOTgxMzI3OCwicGF0aCI6Ii8xMjk0NzYwLzM0NDUzMjIyOC0zZmI1ZDhlNC05OTgyLTQ2YmUtOWY3Ny1kZDA2MGI2OTJkNWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDFUMDU1NDM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTAxMDgxZWViNzNmNzVjZmMyOTY3Mzc0YmNmMzNiMTFiNzc1ODFlNTEwYjFmYjdmYjI2Y2NhMDk3YTAyNGIyYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-6k1iFTgnYEPODT3OKHC9Kwv_fnKB-_2ZOUIBS9n5Kc)
> 
> ② Check酱是 Server酱赞助开发的，如果 Server酱一直挣不到钱，Check酱可能就没了。一个月就3块钱也不多吧

这里只有回调url，但是没有填写json数据结构的地方啊

**Comment by wintsa123** [comment]
> ① Check酱是支持webhook的，就在设置页面。
> 
> ![image](https://private-user-images.githubusercontent.com/1294760/344532228-3fb5d8e4-9982-46be-9f77-dd060b692d5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MTM1NzgsIm5iZiI6MTcxOTgxMzI3OCwicGF0aCI6Ii8xMjk0NzYwLzM0NDUzMjIyOC0zZmI1ZDhlNC05OTgyLTQ2YmUtOWY3Ny1kZDA2MGI2OTJkNWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDFUMDU1NDM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTAxMDgxZWViNzNmNzVjZmMyOTY3Mzc0YmNmMzNiMTFiNzc1ODFlNTEwYjFmYjdmYjI2Y2NhMDk3YTAyNGIyYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-6k1iFTgnYEPODT3OKHC9Kwv_fnKB-_2ZOUIBS9n5Kc)
> 
> ② Check酱是 Server酱赞助开发的，如果 Server酱一直挣不到钱，Check酱可能就没了。一个月就3块钱也不多吧

涨了，一个月8块，我觉得挺多的。毕竟server酱的功能，我也是可以自己手写一个服务出来代替。。。

**Comment by easychen** [comment]
> > ① Check酱是支持webhook的，就在设置页面。
> > ![image](https://private-user-images.githubusercontent.com/1294760/344532228-3fb5d8e4-9982-46be-9f77-dd060b692d5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MTM1NzgsIm5iZiI6MTcxOTgxMzI3OCwicGF0aCI6Ii8xMjk0NzYwLzM0NDUzMjIyOC0zZmI1ZDhlNC05OTgyLTQ2YmUtOWY3Ny1kZDA2MGI2OTJkNWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDFUMDU1NDM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTAxMDgxZWViNzNmNzVjZmMyOTY3Mzc0YmNmMzNiMTFiNzc1ODFlNTEwYjFmYjdmYjI2Y2NhMDk3YTAyNGIyYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-6k1iFTgnYEPODT3OKHC9Kwv_fnKB-_2ZOUIBS9n5Kc)
> > ② Check酱是 Server酱赞助开发的，如果 Server酱一直挣不到钱，Check酱可能就没了。一个月就3块钱也不多吧
> 
> 涨了，一个月8块，我觉得挺多的。毕竟server酱的功能，我也是可以自己手写一个服务出来代替。。。

年付，算下来3块多。

其实我觉得，check酱和绝大部分程序，程序员也能自己手写一个。
