### ISSUE TITLE
云端CPU占用100%

### ISSUE THREAD

**Issue by luckiestone** [easychen/checkchan-dist#83]
云端配置不算太低，换了两个不同配置的服务器都是100%的CPU占用，查看了下是因为Chrome占用，请问是否有设置的方法降低CPU占用，VPS一直100%有点不好意思。此外，我设置的间隔为10小时，一共五个任务，几乎都是同时添加的，不知为何没有任务在运行也极高占用。
部署方式：docker-compose

**Comment by easychen** [comment]
这个可能是chrome版本的问题，不行就切回之前的 [2022.10.15.12.53](https://hub.docker.com/layers/easychen/checkchan/2022.10.15.12.53/images/sha256-573880ed373cdb860ad22cd8e36923b86e53e780fb85bed2114c2e78155d822d?context=explore) 版本吧

**Comment by luckiestone** [comment]
> 这个可能是chrome版本的问题，不行就切回之前的 [2022.10.15.12.53](https://hub.docker.com/layers/easychen/checkchan/2022.10.15.12.53/images/sha256-573880ed373cdb860ad22cd8e36923b86e53e780fb85bed2114c2e78155d822d?context=explore) 版本吧

非常感谢，现在准备改用自定义脚本的方式了，监测URL应该通过什么变量获取到呀，我尝试了下，没有获取到。

**Comment by easychen** [comment]
我更新了一个新版本，可以试试 [2024.10.10.17.20](https://hub.docker.com/layers/easychen/checkchan/2024.10.10.17.20/images/sha256-7b863f12294013c3e3ccac57a908431498d1217eecf09ebad15a07b8c60505af?context=explore)
